version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"

  web:
    restart: always
    build: .
    command: bash -c "python manage.py makemigrations &&python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - db
    restart: on-failure

