# Generated by Django 3.2.8 on 2021-10-15 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherinfo',
            old_name='town',
            new_name='city',
        ),
    ]
