# Generated by Django 3.2.8 on 2021-10-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0002_auto_20211015_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weatherinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather_forecast.weatherinfo')),
            ],
            bases=('weather_forecast.weatherinfo',),
        ),
    ]
