# Generated by Django 3.2.8 on 2021-10-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0002_rename_town_weatherinfo_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='tempirature',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
