# Generated by Django 3.2.8 on 2021-10-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0003_auto_20211015_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherinfo',
            name='tempirature',
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='humidity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='temperature',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
