# Generated by Django 3.2.8 on 2021-10-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0003_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
